// Project workspace drift detection + additive migration.
// Anchor: cli/src/workspace-drift.js
//
// WHY THIS EXISTS
// ---------------
// `.hopper/` is scaffolded ONCE and then owned by the project, but the plugin's
// contract with those files keeps evolving: new machine-parsed columns, new
// fail-closed sections, generated docs going stale, and — worst — the same text
// changing meaning underneath. Nothing ever told a project it had fallen behind.
//
// The cost is measured, not hypothetical:
//   - v0.40.0 turned `## Approved Vendors` into a fail-closed gate. Every project
//     scaffolded before it silently stopped dispatching. hopper's OWN dogfood
//     workspace was among them and nobody noticed for weeks.
//   - batch 2 (2026-07) added the machine-parsed `Effort policy` / `Model rule`
//     columns. agents.js treats them as optional and skips them silently, so the
//     `--model` / `--reasoning` fallback chains just quietly lost a level. A real
//     project was found still on a v0.28.0 scaffold — 18 releases behind — and the
//     resulting `effective_selector: null` got misdiagnosed as a dispatch bug.
//
// MIGRATION.md documents all of this, but it is PASSIVE: it only helps someone who
// already suspects they need it. This module is the active half.
//
// DESIGN RULES (a governance file is not a config file)
// -----------------------------------------------------
// `.hopper/AGENTS.md` carries recorded human approvals — who approved which vendor,
// when. A migrator that rewrites it must be boring and auditable:
//   * ADDITIVE ONLY. Add a missing column (filled with the out-of-band `(bind per
//     project)` marker), add a missing section, regenerate a 100%-generated file.
//     NEVER change a bound value, delete a row, or flip an `Approved` cell.
//   * BACK UP before writing, into `.hopper/.migrations/`.
//   * IDEMPOTENT. Running twice is a no-op.
//   * REFUSE rather than guess. If the target structure cannot be located
//     unambiguously, report it and print the manual steps instead.
// Nothing here runs automatically; `--migrate-config` is always explicit.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderRulesMarkdown } from './rules.js';
import { SCAFFOLD_TASK_TYPES, taskFrame } from './scaffold.js';
import { SCAFFOLD_STAMP_PREFIX, currentVersion, compareVersionDesc, isOlder } from './version.js';

// Re-exported so existing callers/tests keep their import site. The definitions
// live in version.js because scaffold.js needs them too (see that file's header).
export { SCAFFOLD_STAMP_PREFIX, currentVersion, compareVersionDesc, isOlder };

// Both version captures END on a non-dot character. Without that, a version
// followed by a sentence-ending period — `Generated by hopper v0.28.0. Oldest
// capability staleAfter: ...` — captures `0.28.0.` and every later comparison
// silently works off a malformed version string.
const STAMP_RE = /<!--\s*hopper-scaffold-version:\s*([0-9][0-9A-Za-z.\-+]*[0-9A-Za-z])\s*-->/;
const DISPATCH_STAMP_RE = /Generated by hopper v([0-9][0-9A-Za-z.\-+]*[0-9A-Za-z])/;

/** The out-of-band marker the parsers treat as "deliberately unbound". */
export const OOB_MARKER = '(bind per project)';

/**
 * Read the scaffold provenance stamp out of AGENTS.md content.
 * Returns null when absent — which is itself the signal that the file predates
 * stamping (i.e. is at least as old as the version that introduced it).
 * @param {string} content
 * @returns {string|null}
 */
export function readScaffoldStamp(content) {
  const m = typeof content === 'string' ? content.match(STAMP_RE) : null;
  return m ? m[1] : null;
}

/** Version of the generator recorded in a DISPATCH.md header, or null. */
export function readDispatchStamp(content) {
  const m = typeof content === 'string'
    ? content.match(DISPATCH_STAMP_RE)
    : null;
  return m ? m[1] : null;
}

// ─── Markdown table surgery ──────────────────────────────────────────────────

/**
 * Locate the "Task-type → vendor default preference" table and return its line
 * span plus parsed rows. Returns null when it cannot be found unambiguously —
 * callers must REFUSE rather than guess.
 *
 * Deliberately mirrors agents.js's own section detection so the migrator and the
 * parser can never disagree about which table is "the" preferences table.
 */
export function locatePreferencesTable(content) {
  const lines = String(content).split(/\r?\n/);
  let inSection = false;
  let headerIdx = -1;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i].trim();
    if (/^##\s+/.test(line)) {
      inSection = /task-type.*vendor.*preference|task-type.*preference|vendor default preference/i.test(line);
      continue;
    }
    if (!inSection || !line.startsWith('|')) continue;
    const cells = line.replace(/^\|/, '').replace(/\|\s*$/, '').split('|').map((c) => c.trim().toLowerCase());
    const hasTaskType = cells.some((c) => c === 'task-type' || c === 'task type');
    const hasVendor = cells.some((c) => ['default vendor', 'vendor', 'preferred vendor'].includes(c));
    if (hasTaskType && hasVendor) { headerIdx = i; break; }
  }
  if (headerIdx === -1) return null;

  const sepIdx = headerIdx + 1;
  if (!lines[sepIdx] || !/^\s*\|[\s:|-]+\|\s*$/.test(lines[sepIdx])) return null;

  let end = sepIdx;
  for (let i = sepIdx + 1; i < lines.length; i += 1) {
    if (!lines[i].trim().startsWith('|')) break;
    end = i;
  }
  const header = lines[headerIdx].replace(/^\s*\|/, '').replace(/\|\s*$/, '').split('|').map((c) => c.trim());
  return { lines, headerIdx, sepIdx, endIdx: end, header };
}

/**
 * Append columns to a markdown table, filling every existing body row with
 * `fill`. Pure string transform over the located table.
 */
function addColumns(loc, columns, fill) {
  const out = [...loc.lines];
  const pad = columns.map(() => ` ${fill} `).join('|');
  out[loc.headerIdx] = `${out[loc.headerIdx].trimEnd().replace(/\|\s*$/, '')}| ${columns.join(' | ')} |`;
  // The separator needs the SAME cell count as the header. Appending the dashes
  // without a leading `|` merges the last existing cell with the first new one
  // and silently produces a table one column short — markdown renderers then drop
  // the extra header cells, and a reader sees a table that looks fine but is not.
  out[loc.sepIdx] = `${out[loc.sepIdx].trimEnd().replace(/\|\s*$/, '')}|${columns.map(() => '---').join('|')}|`;
  for (let i = loc.sepIdx + 1; i <= loc.endIdx; i += 1) {
    out[i] = `${out[i].trimEnd().replace(/\|\s*$/, '')}|${pad}|`;
  }
  return out.join('\n');
}

// ─── Migration registry ──────────────────────────────────────────────────────
//
// Each entry is small and independently testable. `detect` returns a reason
// string when the migration APPLIES, or null when it does not (already done, or
// not relevant). `apply` returns the new file content, or throws to refuse.

/** @type {Array<{id:string,file:string,since:string,breaking:boolean,title:string,detect:Function,apply:Function}>} */
export const MIGRATIONS = [
  {
    id: 'scaffold-stamp',
    file: 'AGENTS.md',
    since: '0.48.0',
    breaking: false,
    title: 'Write / refresh the scaffold version stamp (the baseline every later drift check reads)',
    // Fires both when the stamp is ABSENT and when it is STALE. Refreshing matters:
    // migrations detect structurally (does the column exist?), so a stale stamp does
    // not currently cause wrong decisions — but it would keep reporting an old
    // baseline for a workspace that has in fact been fully migrated, which is the
    // same species of misleading state this whole module exists to remove.
    detect: (content, { version }) => {
      const stamp = readScaffoldStamp(content);
      if (!stamp) return 'AGENTS.md carries no version stamp — there is no baseline to measure drift against';
      return isOlder(stamp, version)
        ? `stamp is still ${stamp} while the plugin is v${version} — refresh it so the drift baseline is accurate`
        : null;
    },
    apply: (content, { version }) => {
      const stamp = `<!-- ${SCAFFOLD_STAMP_PREFIX} ${version} -->`;
      if (readScaffoldStamp(content)) return String(content).replace(STAMP_RE, stamp);
      const lines = String(content).split(/\r?\n/);
      // Place it right after the H1 so it is the first thing both a human and a
      // parser meet. Falls back to the very top for a file with no H1.
      const h1 = lines.findIndex((l) => /^#\s+/.test(l));
      const at = h1 === -1 ? 0 : h1 + 1;
      lines.splice(at, 0, '', stamp);
      return lines.join('\n');
    },
  },
  {
    id: 'task-policy-columns',
    file: 'AGENTS.md',
    since: '0.36.0',
    breaking: false,
    title: 'Add the Effort policy / Model rule columns (the batch-2 machine-parsed cells)',
    detect: (content) => {
      const loc = locatePreferencesTable(content);
      if (!loc) return null;
      const lower = loc.header.map((h) => h.toLowerCase());
      const missing = ['effort policy', 'model rule'].filter((c) => !lower.includes(c));
      return missing.length
        ? `task-type table is missing the ${missing.join(' / ')} column(s) — the second level of the --reasoning/--model fallback chain is dead`
        : null;
    },
    apply: (content) => {
      const loc = locatePreferencesTable(content);
      if (!loc) throw new Error('cannot locate the task-type preference table (its structure looks hand-edited) — add the columns manually, see MIGRATION.md');
      const lower = loc.header.map((h) => h.toLowerCase());
      const cols = ['Effort policy', 'Model rule'].filter((c) => !lower.includes(c.toLowerCase()));
      // Filled with the OOB marker, never a guessed value: which effort and which
      // model a project wants is a project decision, and this migrator does not
      // get to make it. `--setup`'s Task-type policy lint will then show them as
      // `unbound`, which is the honest state.
      return addColumns(loc, cols, OOB_MARKER);
    },
  },
  {
    id: 'approved-vendors-section',
    file: 'AGENTS.md',
    since: '0.40.0',
    breaking: true,
    title: 'Add the ## Approved Vendors section (a fail-closed gate since v0.40.0)',
    detect: (content) => (/^##\s+.*approved vendors/im.test(String(content))
      ? null
      : 'no "## Approved Vendors" section — since v0.40.0 this refuses every dispatch in this project'),
    apply: (content) => {
      // Added EMPTY on purpose. This section is a record of human approval; a
      // migrator that pre-approved vendors would manufacture consent that was
      // never given, and it is the one gate standing between a queue and someone
      // else's CLI. An empty table still fails closed — the operator must fill it.
      const section = [
        '',
        '## Approved Vendors',
        '',
        '<!-- Since v0.40.0 this section is a fail-closed gate: absent, or present without an',
        '     Approved=yes row, means every dispatch is refused — an explicit --vendor does not',
        '     bypass it. Added by `hopper-dispatch --migrate-config` and DELIBERATELY LEFT EMPTY:',
        '     approving a vendor is a human decision, and a migrator that pre-filled it would',
        '     manufacture consent that was never given. Dispatch stays refused until you fill it',
        '     in — that is correct, not a bug. -->',
        '',
        '| Vendor | Approved | Approved by | Date | Scope / Notes |',
        '|---|---|---|---|---|',
        `| (fill in) | no | — | — | ${OOB_MARKER} |`,
        '',
      ].join('\n');
      const lines = String(content).split(/\r?\n/);
      // Insert before the first "## " that is not the H1, so it lands high in the
      // file rather than being buried after the tables it gates.
      const at = lines.findIndex((l) => /^##\s+/.test(l));
      if (at === -1) return `${content.replace(/\s*$/, '')}\n${section}`;
      lines.splice(at, 0, ...section.split('\n'));
      return lines.join('\n');
    },
  },
  {
    id: 'dispatch-md-regenerate',
    file: 'DISPATCH.md',
    since: 'always',
    breaking: false,
    title: 'Regenerate DISPATCH.md (rendered entirely from the adapters — no hand-written content to lose)',
    detect: (content, { version }) => {
      if (content == null) return 'DISPATCH.md is missing';
      const stamp = readDispatchStamp(content);
      if (!stamp) return 'DISPATCH.md carries no generator version marker';
      return isOlder(stamp, version)
        ? `DISPATCH.md was generated by v${stamp}, plugin is v${version} — the adapter facts it states may have changed`
        : null;
    },
    // Wholesale regeneration is safe here and ONLY here: this file is rendered
    // from the live adapters and carries no project-authored content. That is
    // also why its staleness is the most dangerous kind — a v0.28.0 copy told
    // readers to "prefer codex -s read-only for a genuinely locked-down review",
    // which on Windows is the exact opposite of what codex does today.
    apply: (_content, { version }) => renderRulesMarkdown({ version }),
  },
  {
    id: 'task-frames',
    file: 'tasks/',
    since: '0.49.0',
    breaking: false,
    title: 'Add task-type frames this plugin ships but the project does not have',
    // A task-type only becomes dispatchable once `.hopper/tasks/<type>.md` exists,
    // so a project that upgrades gets the new TYPE in the registry but no FRAME to
    // dispatch it with — and `--task-types` (which lists the project's frames, not
    // the plugin's) keeps showing the old set with nothing explaining why.
    // Frames are generated, contain no project-authored content, and are only ever
    // ADDED here: an existing frame is left exactly as the project wrote it.
    detect: (_content, { missingFrames = [] }) => (missingFrames.length
      ? `missing task-type frame(s): ${missingFrames.join(', ')} — these types cannot be dispatched until the frames exist`
      : null),
    apply: null,   // handled by applyWorkspaceMigrations: writes N files, not one
  },
];

// ─── Planning + applying ─────────────────────────────────────────────────────

function readIfExists(p) {
  try { return existsSync(p) ? readFileSync(p, 'utf-8') : null; } catch (_) { return null; }
}

/**
 * Which migrations apply to this workspace. Pure I/O read; changes nothing.
 *
 * @param {string} hopperDir
 * @param {object} [o]
 * @param {string} [o.version] running plugin version (injectable for tests)
 * @returns {{ hopperDir: string, version: string, stamp: string|null,
 *             entries: Array<{id,title,file,since,breaking,reason}>, errors: string[] }}
 */
export function planWorkspaceMigrations(hopperDir, { version = currentVersion() } = {}) {
  const errors = [];
  const agentsPath = join(hopperDir, 'AGENTS.md');
  const agents = readIfExists(agentsPath);
  if (agents == null) errors.push(`${agentsPath} does not exist — is this really a .hopper workspace?`);

  const cache = { 'AGENTS.md': agents, 'DISPATCH.md': readIfExists(join(hopperDir, 'DISPATCH.md')) };
  const missingFrames = missingTaskFrames(hopperDir);
  const entries = [];
  for (const m of MIGRATIONS) {
    const content = cache[m.file];
    if (m.file === 'AGENTS.md' && content == null) continue;
    let reason = null;
    try { reason = m.detect(content, { version, missingFrames }); }
    catch (err) { errors.push(`${m.id}: detection failed — ${err.message}`); continue; }
    if (reason) entries.push({ id: m.id, title: m.title, file: m.file, since: m.since, breaking: m.breaking, reason });
  }
  return { hopperDir, version, stamp: agents ? readScaffoldStamp(agents) : null, entries, errors };
}

/**
 * Apply the planned migrations. `dryRun` computes everything and writes nothing.
 *
 * Ordering follows MIGRATIONS declaration order, and AGENTS.md migrations are
 * chained through the same in-memory buffer so several can land in one pass
 * without re-reading a half-written file.
 *
 * @param {string} hopperDir
 * @param {object} [o]
 * @param {boolean} [o.dryRun]
 * @param {string[]} [o.only]   restrict to these migration ids
 * @param {string} [o.version]
 * @returns {{ applied: Array, refused: Array, backups: string[], dryRun: boolean, results: Record<string,string> }}
 */
export function applyWorkspaceMigrations(hopperDir, { dryRun = true, only = null, version = currentVersion() } = {}) {
  const plan = planWorkspaceMigrations(hopperDir, { version });
  const selected = plan.entries.filter((e) => !only || only.includes(e.id));

  const buffers = {
    'AGENTS.md': readIfExists(join(hopperDir, 'AGENTS.md')),
    'DISPATCH.md': readIfExists(join(hopperDir, 'DISPATCH.md')),
  };
  const applied = [];
  const refused = [];

  const missingFrames = missingTaskFrames(hopperDir);
  const framesWritten = [];
  for (const entry of selected) {
    const m = MIGRATIONS.find((x) => x.id === entry.id);
    if (m.id === 'task-frames') {
      // Multi-file migration: no single buffer to thread through, and every frame is
      // generated content, so it is written directly (still gated on !dryRun below).
      framesWritten.push(...missingFrames);
      applied.push(entry);
      continue;
    }
    try {
      const next = m.apply(buffers[m.file], { version });
      if (typeof next !== 'string' || !next.trim()) throw new Error('migration produced empty content — refusing to write');
      buffers[m.file] = next;
      applied.push(entry);
    } catch (err) {
      // Refusing is a first-class outcome, not a crash: a hand-restructured file
      // is exactly the case where guessing would do damage.
      refused.push({ ...entry, error: err.message });
    }
  }

  const backups = [];
  if (!dryRun && framesWritten.length) {
    // ADD-ONLY: an existing frame is never touched, so there is no project-authored
    // content at risk and nothing to back up.
    writeTaskFrames(hopperDir, framesWritten);
  }
  if (!dryRun && applied.length) {
    const backupDir = join(hopperDir, '.migrations');
    mkdirSync(backupDir, { recursive: true });
    const stampLabel = plan.stamp || 'unstamped';
    // Only buffer-backed migrations are written here. `task-frames` targets a
    // DIRECTORY (many files, all generated) and wrote itself above; leaving it in
    // this set means writeFileSync gets `buffers["tasks/"]` === undefined.
    for (const file of new Set(applied.map((a) => a.file).filter((f) => f in buffers))) {
      const src = join(hopperDir, file);
      const original = readIfExists(src);
      if (original != null) {
        const dest = join(backupDir, `${file}.${stampLabel}.bak`);
        writeFileSync(dest, original, 'utf-8');
        backups.push(dest);
      }
      writeFileSync(src, buffers[file], 'utf-8');
    }
    appendMigrationLog(backupDir, { version, applied, refused, stamp: plan.stamp });
  }

  return { applied, refused, backups, dryRun, results: buffers, plan };
}

/**
 * Task-type frames this plugin ships that the project's `.hopper/tasks/` lacks.
 * A missing frame means the type is in the registry but cannot be dispatched — and
 * `--task-types` reads the PROJECT's frames, so it keeps listing the old set with
 * nothing on screen explaining why the new type is absent.
 * @param {string} hopperDir
 * @returns {string[]}
 */
export function missingTaskFrames(hopperDir) {
  try {
    return SCAFFOLD_TASK_TYPES.filter((t) => !existsSync(join(hopperDir, 'tasks', `${t}.md`)));
  } catch (_) { return []; }
}

/** Write the named frames. Never overwrites one that already exists. */
export function writeTaskFrames(hopperDir, types) {
  const dir = join(hopperDir, 'tasks');
  mkdirSync(dir, { recursive: true });
  const written = [];
  for (const t of types) {
    const p = join(dir, `${t}.md`);
    if (existsSync(p)) continue;
    writeFileSync(p, taskFrame(t), 'utf-8');
    written.push(p);
  }
  return written;
}

/** Append-only migration record. `.hopper/` is treated as audit evidence by real projects. */
function appendMigrationLog(backupDir, { version, applied, refused, stamp }) {
  const logPath = join(backupDir, 'log.md');
  const header = existsSync(logPath) ? '' : '# Migration log\n\nAppended to by `hopper-dispatch --migrate-config`. Append-only — entries are never rewritten.\n';
  const lines = [
    `\n## hopper v${version} (previous stamp: ${stamp || 'none'})`,
    '',
    ...applied.map((a) => `- applied \`${a.id}\` — ${a.title}`),
    ...refused.map((r) => `- REFUSED \`${r.id}\` — ${r.error}`),
    '',
  ];
  try {
    const prev = existsSync(logPath) ? readFileSync(logPath, 'utf-8') : '';
    writeFileSync(logPath, header + prev + lines.join('\n'), 'utf-8');
  } catch (_) { /* the log is a courtesy; never fail a migration over it */ }
}

/**
 * Minimal unified-ish diff for the dry-run view. Line-level, no dependencies —
 * enough for a human to see what would change without pulling in a diff library.
 */
export function simpleDiff(before, after, { context = 2 } = {}) {
  const a = String(before ?? '').split(/\r?\n/);
  const b = String(after ?? '').split(/\r?\n/);
  const out = [];
  let i = 0;
  let j = 0;
  while (i < a.length || j < b.length) {
    if (a[i] === b[j]) { i += 1; j += 1; continue; }
    // Additions: b has lines a does not (the additive-only case).
    const resync = b.indexOf(a[i] ?? '', j);
    if (a[i] !== undefined && resync !== -1) {
      for (let k = Math.max(0, j - context); k < j; k += 1) out.push(`  ${b[k]}`);
      for (let k = j; k < resync; k += 1) out.push(`+ ${b[k]}`);
      j = resync;
      continue;
    }
    if (a[i] !== undefined) out.push(`- ${a[i]}`);
    if (b[j] !== undefined) out.push(`+ ${b[j]}`);
    i += 1;
    j += 1;
  }
  return out;
}
