// Workspace drift detection + additive migration tests.
// Anchor: tests/unit/workspace-drift.test.js
//
// The migrator rewrites a file that records human approvals, so the tests that
// matter most here are the NEGATIVE ones: it must not change a bound value, must
// not pre-approve a vendor, must not write during a dry run, and must refuse
// rather than guess when the structure is unfamiliar.

import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  readScaffoldStamp, readDispatchStamp, compareVersionDesc, isOlder,
  locatePreferencesTable, planWorkspaceMigrations, applyWorkspaceMigrations, simpleDiff,
} from '../../cli/src/workspace-drift.js';
import { parseAgentsContent } from '../../cli/src/agents.js';
import { parseEffortPolicyCell, parseModelRuleCell } from '../../cli/src/policy.js';

const OLD_AGENTS = `# Agent Instances

## Active Agent Instances

| Nickname | UUID | Vendor | Default invocation | Notes |
|----------|------|--------|--------------------|-------|
| \`codex-builder\` | \`-\` | codex | configured adapter | x |

## Task-type → vendor default preference

| Task-type | Default vendor | Why |
|---|---|---|
| \`code-review-adversarial\` | codex-builder | Read-only default |
| \`prd-research\` | codex-builder | Read-only default |
`;

const OLD_DISPATCH = '# Rules\n\n> - Generated by hopper v0.28.0. Oldest capability `staleAfter`: 2026-08-21.\n\nbody\n';

/** A workspace shaped like the real v0.28.0-era ones. */
function oldWorkspace({ agents = OLD_AGENTS, dispatch = OLD_DISPATCH } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'hopper-drift-'));
  const hopperDir = join(root, '.hopper');
  // findHopperDir() requires handoffs/ to distinguish a workspace from the global
  // ~/.hopper cache, so a fixture without it is not a workspace at all.
  mkdirSync(join(hopperDir, 'handoffs'), { recursive: true });
  writeFileSync(join(hopperDir, 'AGENTS.md'), agents);
  if (dispatch != null) writeFileSync(join(hopperDir, 'DISPATCH.md'), dispatch);
  return { root, hopperDir };
}

// ─── stamps + version ordering ───────────────────────────────────────────────

test('readScaffoldStamp: reads the stamp, and null means "predates stamping"', () => {
  assert.equal(readScaffoldStamp('# x\n<!-- hopper-scaffold-version: 0.46.0 -->\n'), '0.46.0');
  assert.equal(readScaffoldStamp(OLD_AGENTS), null);
  assert.equal(readScaffoldStamp(undefined), null);
});

test('version capture stops before a sentence-ending period', () => {
  // `Generated by hopper v0.28.0. Oldest capability ...` — a greedy capture takes
  // `0.28.0.` and every later comparison then runs on a malformed version.
  assert.equal(readDispatchStamp(OLD_DISPATCH), '0.28.0');
  assert.equal(readScaffoldStamp('<!-- hopper-scaffold-version: 1.2.3 -->'), '1.2.3');
});

test('compareVersionDesc: numeric, not lexicographic', () => {
  assert.deepEqual(['0.9.0', '0.10.0'].sort(compareVersionDesc), ['0.10.0', '0.9.0']);
  assert.equal(isOlder('0.28.0', '0.47.0'), true);
  assert.equal(isOlder('0.47.0', '0.47.0'), false);
});

// ─── table location ──────────────────────────────────────────────────────────

test('locatePreferencesTable: finds the preferences table, not the instances table', () => {
  const loc = locatePreferencesTable(OLD_AGENTS);
  assert.ok(loc, 'table located');
  assert.deepEqual(loc.header, ['Task-type', 'Default vendor', 'Why']);
  assert.equal(loc.endIdx - loc.sepIdx, 2, 'two body rows');
});

test('locatePreferencesTable: returns null when the structure is unfamiliar', () => {
  assert.equal(locatePreferencesTable('# no tables here'), null);
  assert.equal(locatePreferencesTable('## Task-type → vendor default preference\n\nprose only\n'), null);
});

// ─── planning ────────────────────────────────────────────────────────────────

test('plan: an old workspace reports every applicable migration, flagging the breaking one', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.0' });
    const ids = plan.entries.map((e) => e.id);
    assert.deepEqual(ids, [
      'scaffold-stamp', 'task-policy-columns', 'approved-vendors-section',
      'dispatch-md-regenerate',
      // The fixture has no tasks/ at all, so every shipped frame is missing.
      'task-frames',
    ]);
    assert.equal(plan.stamp, null);
    assert.equal(plan.entries.find((e) => e.id === 'approved-vendors-section').breaking, true,
      'the v0.40.0 fail-closed gate is the one BREAKING migration');
    assert.equal(plan.errors.length, 0);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('plan: a current workspace reports nothing', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.0' });
    assert.deepEqual(plan.entries, [], 'migration is idempotent');
    assert.equal(plan.stamp, '0.48.0');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

// ─── dry run ─────────────────────────────────────────────────────────────────

test('dry run writes NOTHING to disk', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    const res = applyWorkspaceMigrations(hopperDir, { dryRun: true, version: '0.48.0' });
    assert.ok(res.applied.length > 0, 'it still computes the full result');
    assert.equal(readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8'), OLD_AGENTS, 'file untouched');
    assert.equal(existsSync(join(hopperDir, '.migrations')), false, 'no backup dir created');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('dry run is the DEFAULT (a caller that forgets the flag cannot write)', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { version: '0.48.0' });
    assert.equal(readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8'), OLD_AGENTS);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

// ─── apply: additive-only guarantees ─────────────────────────────────────────

test('apply: adds columns without touching any existing cell', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    const after = readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8');
    // Every original body cell survives verbatim.
    assert.match(after, /\| `code-review-adversarial` \| codex-builder \| Read-only default \|/);
    assert.match(after, /\| `prd-research` \| codex-builder \| Read-only default \|/);
    assert.match(after, /\| Task-type \| Default vendor \| Why \| Effort policy \| Model rule \|/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('apply: the migrated table still parses, with the new columns UNBOUND', () => {
  // The real acceptance test: agents.js must read the result, and the added cells
  // must land as `unbound` rather than as a value the migrator invented.
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    const parsed = parseAgentsContent(readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8'));
    assert.equal(parsed.preferences['code-review-adversarial'], 'codex-builder', 'routing preserved');
    const policy = parsed.policies['code-review-adversarial'];
    assert.equal(parseEffortPolicyCell(policy.effortPolicy, 'codex').status, 'unbound');
    assert.equal(parseModelRuleCell(policy.modelRule).status, 'unbound');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('apply: the separator row keeps the same cell count as the header', () => {
  // Appending dashes without a leading pipe merges two cells and yields a table one
  // column short — it renders fine and is wrong, which is the worst combination.
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    const lines = readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8').split('\n');
    const headerIdx = lines.findIndex((l) => l.includes('| Task-type |'));
    const cells = (l) => l.replace(/^\|/, '').replace(/\|\s*$/, '').split('|').length;
    assert.equal(cells(lines[headerIdx + 1]), cells(lines[headerIdx]), 'separator matches header width');
    assert.equal(cells(lines[headerIdx + 2]), cells(lines[headerIdx]), 'body matches header width');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('apply: Approved Vendors is added EMPTY — never pre-approved', () => {
  // A migrator that filled this in would manufacture consent that was never given,
  // for the one gate standing between a queue and someone else's CLI.
  const { root, hopperDir } = oldWorkspace();
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    const after = readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8');
    assert.match(after, /## Approved Vendors/);
    const parsed = parseAgentsContent(after);
    assert.equal(parsed.approvedVendors.present, true, 'section exists so the error becomes specific');
    assert.equal(parsed.approvedVendors.list.filter((v) => v.approved).length, 0,
      'no vendor is approved by the migration itself');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('apply: backs up the original and appends an audit log entry', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    const res = applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    assert.ok(res.backups.length >= 1);
    for (const b of res.backups) assert.ok(existsSync(b), `${b} exists`);
    const backup = res.backups.find((b) => b.includes('AGENTS.md'));
    assert.equal(readFileSync(backup, 'utf-8'), OLD_AGENTS, 'backup is the untouched original');
    const log = readFileSync(join(hopperDir, '.migrations', 'log.md'), 'utf-8');
    assert.match(log, /applied `task-policy-columns`/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('apply: --only restricts to the named migrations', () => {
  const { root, hopperDir } = oldWorkspace();
  try {
    const res = applyWorkspaceMigrations(hopperDir, { dryRun: false, only: ['scaffold-stamp'], version: '0.48.0' });
    assert.deepEqual(res.applied.map((a) => a.id), ['scaffold-stamp']);
    const after = readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8');
    assert.equal(readScaffoldStamp(after), '0.48.0');
    assert.ok(!/## Approved Vendors/.test(after), 'unselected migrations did not run');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

// ─── refusal ─────────────────────────────────────────────────────────────────

test('a hand-restructured table is REFUSED, not guessed at', () => {
  // detect() finds the section but locate() cannot resolve the table, so the
  // migration must fail loudly for that one entry and leave the file alone.
  const mangled = `# Agent Instances

## Task-type → vendor default preference

Task-type: code-review-adversarial -> codex   (someone rewrote this as prose)
`;
  const { root, hopperDir } = oldWorkspace({ agents: mangled, dispatch: null });
  try {
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.0' });
    // No table to detect against, so the column migration does not even apply.
    assert.ok(!plan.entries.some((e) => e.id === 'task-policy-columns'),
      'an unlocatable table is not reported as a pending column migration');
    const res = applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.0' });
    assert.equal(res.refused.length, 0);
    // The prose survives untouched — additive migrations only inserted around it.
    assert.match(readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8'), /someone rewrote this as prose/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('a missing AGENTS.md is an error, not a silent no-op', () => {
  const root = mkdtempSync(join(tmpdir(), 'hopper-drift-empty-'));
  const hopperDir = join(root, '.hopper');
  mkdirSync(join(hopperDir, 'handoffs'), { recursive: true });
  try {
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.0' });
    assert.equal(plan.errors.length, 1);
    assert.match(plan.errors[0], /AGENTS\.md/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

// ─── diff ────────────────────────────────────────────────────────────────────

test('simpleDiff: marks additions and leaves untouched lines as context', () => {
  const d = simpleDiff('a\nb\nc\n', 'a\nNEW\nb\nc\n');
  assert.ok(d.some((l) => l === '+ NEW'));
  assert.ok(!d.some((l) => l.startsWith('- ')), 'a pure insertion has no deletions');
});

test('stamp is REFRESHED when stale, not only written when absent', () => {
  // A workspace that has been fully migrated must stop reporting the version it
  // was originally scaffolded at. Migrations detect structurally, so a stale stamp
  // does not make a wrong decision today — but it keeps showing an old baseline
  // for an up-to-date workspace, which is the same misleading state this module
  // exists to remove.
  const stamped = OLD_AGENTS.replace('# Agent Instances', '# Agent Instances\n\n<!-- hopper-scaffold-version: 0.46.0 -->');
  const { root, hopperDir } = oldWorkspace({ agents: stamped, dispatch: null });
  try {
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.1' });
    const entry = plan.entries.find((e) => e.id === 'scaffold-stamp');
    assert.ok(entry, 'a stale stamp is reported');
    assert.match(entry.reason, /0\.46\.0/);

    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.48.1' });
    const after = readFileSync(join(hopperDir, 'AGENTS.md'), 'utf-8');
    assert.equal(readScaffoldStamp(after), '0.48.1', 'stamp refreshed in place');
    assert.equal((after.match(/hopper-scaffold-version/g) || []).length, 1, 'exactly one stamp — not appended twice');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('a current stamp is left alone (no churn on every run)', () => {
  const stamped = OLD_AGENTS.replace('# Agent Instances', '# Agent Instances\n\n<!-- hopper-scaffold-version: 0.48.1 -->');
  const { root, hopperDir } = oldWorkspace({ agents: stamped, dispatch: null });
  try {
    const plan = planWorkspaceMigrations(hopperDir, { version: '0.48.1' });
    assert.ok(!plan.entries.some((e) => e.id === 'scaffold-stamp'), 'no work when already current');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('task-frames: a project missing a newly shipped type gets its frame added', async () => {
  // A task-type is only dispatchable once .hopper/tasks/<type>.md exists, and
  // `--task-types` lists the PROJECT's frames — so an upgraded project would show
  // the old set with nothing on screen explaining why the new type is absent.
  const { SCAFFOLD_TASK_TYPES } = await import('../../cli/src/scaffold.js');
  const { missingTaskFrames } = await import('../../cli/src/workspace-drift.js');
  const { root, hopperDir } = oldWorkspace({ dispatch: null });
  try {
    // Give the project every frame EXCEPT the two newest, to model an upgrade.
    mkdirSync(join(hopperDir, 'tasks'), { recursive: true });
    const stale = SCAFFOLD_TASK_TYPES.filter((t) => t !== 'decision-review' && t !== 'tech-research');
    for (const t of stale) writeFileSync(join(hopperDir, 'tasks', `${t}.md`), `# existing ${t}\n`);

    assert.deepEqual(missingTaskFrames(hopperDir).sort(), ['decision-review', 'tech-research']);

    const plan = planWorkspaceMigrations(hopperDir, { version: '0.49.0' });
    const entry = plan.entries.find((e) => e.id === 'task-frames');
    assert.ok(entry, 'reported as pending');
    assert.match(entry.reason, /decision-review/);

    applyWorkspaceMigrations(hopperDir, { dryRun: false, version: '0.49.0' });
    assert.deepEqual(missingTaskFrames(hopperDir), [], 'both frames written');
    assert.match(readFileSync(join(hopperDir, 'tasks', 'decision-review.md'), 'utf-8'), /Task-type: decision-review/);
    // ADD-ONLY: a frame the project already had is left exactly as it wrote it.
    assert.equal(readFileSync(join(hopperDir, 'tasks', 'spec-write.md'), 'utf-8'), '# existing spec-write\n');
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test('task-frames: dry run writes no frame files', () => {
  const { root, hopperDir } = oldWorkspace({ dispatch: null });
  try {
    applyWorkspaceMigrations(hopperDir, { dryRun: true, version: '0.49.0' });
    assert.equal(existsSync(join(hopperDir, 'tasks')), false, 'no tasks/ dir created during a dry run');
  } finally { rmSync(root, { recursive: true, force: true }); }
});
